backend:
  name: github
  branch: Ashley1985/archive

media_folder: "docs/public/media" # The folder where uploaded media files will be stored
public_folder: "public/media" # The public URL for accessing uploaded media files

collections:
  - name: "docs" # The name of the collection (corresponds to the directory name where your markdown files are located)
    label: "Docs" # The label for the collection in the CMS UI
    folder: "docs" # The folder where your markdown files are located
    create: true # Allow creating new documents in this collection
    slug: "{{slug}}" # The URL slug for new documents (uses the filename without the extension)
    fields:
      - { name: "title", label: "Title", widget: "string" } # A required string field for the document title
      - { name: "date", label: "Date", widget: "datetime" } # A required date/time field for the document date
      - { name: "description", label: "Description", widget: "text" } # An optional text field for the document description
      - { name: "body", label: "Body", widget: "markdown" } # The main markdown content for the document
